#!/bin/bash
# BPM match — /v1/audio/bpm-match end-to-end.
#
#     bash tests/integration/e2e_bpm_match.sh

set -eo pipefail

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=harness.sh
source "${_DIR}/harness.sh"
# shellcheck source=common.sh
source "${_DIR}/common.sh"

FIXTURE="${_DIR}/.fixtures/audio.wav"
# beat_120.wav is generated by harness_start (via _harness_generate_fixtures).
BEAT_FIXTURE="${_DIR}/.fixtures/beat_120.wav"

harness_start "librosa-analyze,stretch"

# ── returns WAV with required JSON fields ─────────────────────────────────────

test_bpm_match_returns_wav() {
    local tmpout code
    tmpout=$(mktemp)
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${BEAT_FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${BEAT_FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"target_bpm\":120.0,\"output_path\":\"$_out\"}" \
        -o "$tmpout" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "$tmpout" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "200" "bpm-match -> 200" || { rm -f "$tmpout"; return 1; }
    if [ "$(stat -c%s "$tmpout")" -lt 100 ]; then
        echo "  FAIL: staged file too small (suspect not WAV)"
        rm -f "$tmpout"; return 1
    fi
    echo "OK: bpm_match_returns_wav ($(stat -c%s "$tmpout") bytes)"
    rm -f "$tmpout"
}

# ── output_path returns JSON with source/target BPM metadata ─────────────────

test_bpm_match_json_metadata() {
    local body src_bpm target_bpm
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${BEAT_FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${BEAT_FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    body=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"target_bpm\":140.0,\"output_path\":\"bpm/matched.wav\"}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    src_bpm=$(echo "$body" | jq -r '.source_bpm // empty')
    target_bpm=$(echo "$body" | jq -r '.target_bpm // empty')
    if [ -z "$src_bpm" ] || [ -z "$target_bpm" ]; then
        echo "  FAIL: missing BPM metadata; body: $body"; return 1
    fi
    if ! echo "$body" | jq -e '.target_bpm == 140.0' >/dev/null 2>&1; then
        echo "  FAIL: target_bpm mismatch; body: $body"; return 1
    fi
    echo "OK: bpm_match_json_metadata (source=${src_bpm} target=${target_bpm})"
}

# ── pitch_semitones preserved in output ───────────────────────────────────────

test_bpm_match_with_pitch() {
    local code
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${BEAT_FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${BEAT_FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"target_bpm\":100.0,\"pitch_semitones\":2.0,\"output_path\":\"$_out\"}" \
        -o "/dev/null" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "/dev/null" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "200" "bpm-match with pitch -> 200" || return 1
    echo "OK: bpm_match_with_pitch"
}

# ── output_format=mp3 ─────────────────────────────────────────────────────────

test_bpm_match_output_format_mp3() {
    local code tmpout
    tmpout=$(mktemp)
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${BEAT_FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${BEAT_FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"target_bpm\":120.0,\"output_format\":\"mp3\",\"output_path\":\"$_out\"}" \
        -o "$tmpout" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "$tmpout" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "200" "bpm-match mp3 -> 200" || { rm -f "$tmpout"; return 1; }
    if [ ! -s "$tmpout" ]; then
        echo "  FAIL: empty mp3"; rm -f "$tmpout"; return 1
    fi
    echo "OK: bpm_match_output_format_mp3 ($(stat -c%s "$tmpout") bytes)"
    rm -f "$tmpout"
}

# ── target_bpm <= 0 → 400 ────────────────────────────────────────────────────

test_bpm_match_zero_target_400() {
    local code
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"target_bpm\":0,\"output_path\":\"$_out\"}" \
        -o "/dev/null" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "/dev/null" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    [[ "$code" = "400" || "$code" = "422" ]] && echo "  OK: $target_bpm=0 -> 422 (code=$code)" || { echo "  FAIL: $target_bpm=0 -> 422 expected 400 or 422, got $code"; return 1; } || return 1
    echo "OK: bpm_match_zero_target_400"
}

# ── target_bpm missing → 422 ─────────────────────────────────────────────────

test_bpm_match_missing_target_422() {
    local code
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"output_path\":\"$_out\"}" \
        -o "/dev/null" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "/dev/null" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "422" "missing target_bpm -> 422" || return 1
    echo "OK: bpm_match_missing_target_422"
}

# ── missing file → 400 ───────────────────────────────────────────────────────

test_bpm_match_missing_file_404() {
    local code
    code=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"file_path\":\"no/such.wav\",\"target_bpm\":120.0}" -o "/dev/null" -w "%{http_code}" --max-time 30 "${AUDIOLLA_BASE_URL}/v1/audio/bpm-match")
    [[ "$code" = "400" || "$code" = "404" || "$code" = "422" ]] || { echo "  FAIL: missing file -> got $code"; return 1; }
    echo "OK: bpm_match_missing_file_404 (code=$code)"
}

harness_run_tests \
    test_bpm_match_returns_wav \
    test_bpm_match_json_metadata \
    test_bpm_match_with_pitch \
    test_bpm_match_output_format_mp3 \
    test_bpm_match_zero_target_400 \
    test_bpm_match_missing_target_422 \
    test_bpm_match_missing_file_404
