#!/bin/bash
# Mastering end-to-end — both modes (reference via matchering, chain via
# pedalboard). CPU-only.
#
# Fixture: tests/integration/.fixtures/audio.wav.
# matchering needs a second reference file; we synthesize a louder variant of
# the same fixture inside the container if needed — for matchering's
# equality-check to pass, the two MUST NOT be byte-identical.
#
#     bash tests/integration/e2e_mastering.sh

set -eo pipefail

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=harness.sh
source "${_DIR}/harness.sh"
# shellcheck source=common.sh
source "${_DIR}/common.sh"

FIXTURE="${_DIR}/.fixtures/audio.wav"
REFERENCE="${_DIR}/.fixtures/audio_ref.wav"

harness_start "matchering,pedalboard-chain,librosa-analyze"

_skip_if_no_fixture() {
    if [ ! -f "$FIXTURE" ]; then
        echo "  SKIP: fixture not found at ${FIXTURE}"
        return 0
    fi
    return 1
}

# Reference audio is auto-generated by harness_start (see harness.sh
# `_harness_generate_fixtures`) — no local helper needed.

# ── /healthz wired ───────────────────────────────────────────────────────────

test_healthz_has_engines() {
    local out
    out=$(audiolla_get "/healthz") || { echo "  FAIL: /healthz unreachable"; return 1; }
    assert_contains "$out" "matchering" "/healthz lists matchering" || return 1
    assert_contains "$out" "pedalboard-chain" "/healthz lists pedalboard-chain" || return 1
    echo "OK: healthz_has_engines"
}

# ── /v1/audio/master mode=chain preset=transparent → RIFF ────────────────────

test_master_chain_transparent() {
    _skip_if_no_fixture && return 0
    local tmp code
    tmp=$(mktemp -t audiolla-master.XXXXXX) || return 2
    # shellcheck disable=SC2064
    trap "rm -f '$tmp'" RETURN
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"mode\":\"chain\",\"preset\":\"transparent\",\"output_format\":\"wav\",\"output_path\":\"$_out\"}" \
        -o "$tmp" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/master")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "$tmp" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "200" "master chain transparent -> 200" || return 1
    local head4
    head4=$(head -c 4 "$tmp" | od -An -c | tr -d ' \n')
    assert_eq "$head4" "RIFF" "transparent → RIFF" || return 1
    echo "OK: master_chain_transparent"
}

# ── /v1/audio/master mode=chain preset=loud → RIFF ───────────────────────────

test_master_chain_loud() {
    _skip_if_no_fixture && return 0
    local tmp code
    tmp=$(mktemp -t audiolla-master.XXXXXX) || return 2
    # shellcheck disable=SC2064
    trap "rm -f '$tmp'" RETURN
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"mode\":\"chain\",\"preset\":\"loud\",\"output_path\":\"$_out\"}" \
        -o "$tmp" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/master")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "$tmp" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    assert_eq "$code" "200" "master chain loud -> 200" || return 1
    echo "OK: master_chain_loud"
}

# ── Unknown preset → 400 ─────────────────────────────────────────────────────

test_master_unknown_preset_400() {
    _skip_if_no_fixture && return 0
    local code
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"mode\":\"chain\",\"preset\":\"not-a-preset\",\"output_path\":\"$_out\"}" \
        -o "/dev/null" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/master")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "/dev/null" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    # Handler-level unknown-preset returns 400 (not Pydantic 422).
    assert_eq "$code" "400" "unknown preset -> 400" || return 1
    echo "OK: master_unknown_preset_400"
}

# ── Reference mode without reference file → 400 ──────────────────────────────

test_master_reference_missing_file_422() {
    _skip_if_no_fixture && return 0
    local code
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"mode\":\"reference\",\"output_path\":\"$_out\"}" \
        -o "/dev/null" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/master")
    # v1.0.0: download the staged output to satisfy the test's -o expectation
    curl -sf -o "/dev/null" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || true
    # Handler-level "must provide exactly one of: reference, reference_path, reference_url" → 400.
    assert_eq "$code" "400" "reference mode w/o reference -> 400" || return 1
    echo "OK: master_reference_missing_file_400"
}

# ── /v1/audio/master mode=reference with a real reference → RIFF ─────────────

test_master_reference_real() {
    # v1.0.0 secondary fixture stage
    curl -sf -X PUT --data-binary "@${REFERENCE}" -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/secondary/$(basename "${REFERENCE}")" >/dev/null || true
    _skip_if_no_fixture && return 0
    if [ ! -f "$REFERENCE" ]; then
        echo "  SKIP: reference fixture not present at $REFERENCE"
        return 0
    fi
    # Measure the reference's LUFS first — that's the "expected" target for
    # matchering: reference-based mastering should drive the target's LUFS
    # toward the reference's LUFS. Phase doc gate: within 3 dB.
    local ref_lufs
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${REFERENCE}")"
    curl -sf -X PUT --data-binary "@${REFERENCE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    ref_lufs=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\"}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/loudness")
    if [ -z "$ref_lufs" ] || [ "$ref_lufs" = "null" ]; then
        echo "  FAIL: could not measure reference LUFS for comparison"
        return 1
    fi

    local tmp code
    tmp=$(mktemp -t audiolla-master.XXXXXX) || return 2
    # shellcheck disable=SC2064
    trap "rm -f '$tmp'" RETURN
    # v1.0.0: pre-stage the fixture via /v1/files, build JSON body
    local _stage="uploads/$(basename "${FIXTURE}")"
    local _out="out/result-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${FIXTURE}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_stage}" >/dev/null || true
    code=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_stage\",\"mode\":\"reference\",\"reference_path\":\"secondary/$(basename "${REFERENCE}")\",\"output_path\":\"$_out\"}" \
        -o "$tmp" \
        -w "%{http_code}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/master")
    assert_eq "$code" "200" "master reference -> 200" || return 1
    # Pull the staged result down for LUFS comparison.
    local out_local
    out_local=$(mktemp -t audiolla-master-out.XXXXXX)
    curl -sf -o "$out_local" "${AUDIOLLA_BASE_URL}/v1/files/${_out}" || {
        echo "  FAIL: could not fetch staged master output"
        rm -f "$out_local"; return 1
    }
    local head4
    head4=$(head -c 4 "$out_local" | od -An -c | tr -d ' \n')
    if [ "$head4" != "RIFF" ]; then
        echo "  FAIL: reference master → RIFF: expected 'RIFF', got '$head4'"
        rm -f "$out_local"; return 1
    fi

    # Re-measure the mastered output's LUFS and assert it's within 3 dB of
    # the reference's LUFS (phase doc §1.7 e2e_mastering gate).
    local out_lufs
    local _out_stage="loudness-check/master-out-$$-$RANDOM.wav"
    curl -sf -X PUT --data-binary "@${out_local}" \
        -H "Content-Type: application/octet-stream" \
        "${AUDIOLLA_BASE_URL}/v1/files/${_out_stage}" >/dev/null || true
    rm -f "$out_local"
    out_lufs=$(curl -s -X POST \
        -H "Content-Type: application/json" \
        -d "{\"file_path\":\"$_out_stage\"}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/loudness" | jq -r '.loudness_lufs')
    if [ -z "$out_lufs" ] || [ "$out_lufs" = "null" ]; then
        echo "  FAIL: could not measure mastered output LUFS"
        return 1
    fi
    local ref_lufs_num
    ref_lufs_num=$(echo "$ref_lufs" | jq -r '.loudness_lufs')
    if ! awk -v r="$ref_lufs_num" -v o="$out_lufs" \
        'BEGIN{d=o-r; if(d<0) d=-d; exit (d<=3.0) ? 0 : 1}'; then
        echo "  FAIL: mastered LUFS ${out_lufs} not within 3 dB of reference ${ref_lufs_num}"
        return 1
    fi
    echo "OK: master_reference_real (ref=${ref_lufs_num} out=${out_lufs} dB)"
}

harness_run_tests \
    test_healthz_has_engines \
    test_master_chain_transparent \
    test_master_chain_loud \
    test_master_unknown_preset_400 \
    test_master_reference_missing_file_422 \
    test_master_reference_real
