#!/bin/bash
# DJ prep endpoint — BPM + key + LUFS + Camelot wheel.
# Requires librosa-analyze + chord-detect engines.
#
#     bash tests/integration/e2e_dj_prep.sh

set -eo pipefail

_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=harness.sh
source "${_DIR}/harness.sh"
# shellcheck source=common.sh
source "${_DIR}/common.sh"

FIXTURE="${_DIR}/.fixtures/audio.wav"
# beat_120.wav is generated by harness_start (via _harness_generate_fixtures).
BEAT_FIXTURE="${_DIR}/.fixtures/beat_120.wav"

harness_start "librosa-analyze,chord-detect"

# No-op: beat_120.wav is always generated by the harness before tests run.
build_beat_fixture() { return 0; }

# ── response has all expected keys ───────────────────────────────────────────

test_dj_prep_response_shape() {
    local body
    body=$(curl -s --max-time 60 -X POST \
        -F "file=@${FIXTURE}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/dj-prep")
    for field in bpm key camelot integrated_lufs; do
        if ! echo "$body" | jq -e "has(\"$field\")" >/dev/null 2>&1; then
            echo "  FAIL: field '$field' missing; body: $body"; return 1
        fi
    done
    echo "OK: dj_prep_response_shape"
}

# ── click track: BPM is ~120 ──────────────────────────────────────────────────

test_dj_prep_click_track_bpm() {
    build_beat_fixture || return 1
    local body bpm
    body=$(curl -s --max-time 90 -X POST \
        -F "file=@${BEAT_FIXTURE}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/dj-prep")
    bpm=$(echo "$body" | jq -r '.bpm // empty')
    if [ -z "$bpm" ] || [ "$bpm" = "null" ]; then
        echo "  FAIL: bpm is null; body: $body"; return 1
    fi
    # Expect BPM in range [100, 150] for the 120BPM click track.
    if ! echo "$body" | jq -e '.bpm > 100 and .bpm < 150' >/dev/null 2>&1; then
        echo "  FAIL: bpm $bpm not in [100,150]; body: $body"; return 1
    fi
    echo "OK: dj_prep_click_track_bpm (bpm=${bpm})"
}

# ── integrated_lufs is a number for a real audio file ────────────────────────

test_dj_prep_lufs_is_number() {
    local body
    body=$(curl -s --max-time 60 -X POST \
        -F "file=@${FIXTURE}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/dj-prep")
    if ! echo "$body" | jq -e '.integrated_lufs | (. == null or type == "number")' >/dev/null 2>&1; then
        echo "  FAIL: integrated_lufs not null or number; body: $body"; return 1
    fi
    echo "OK: dj_prep_lufs_is_number (lufs=$(echo "$body" | jq -r '.integrated_lufs'))"
}

# ── missing engine → 404 ─────────────────────────────────────────────────────

test_dj_prep_missing_engine_with_bad_engines() {
    # We can't easily reconfigure engines at runtime, so just verify the
    # endpoint path exists and returns a meaningful structure.
    local body
    body=$(curl -s --max-time 60 -X POST \
        -F "file=@${FIXTURE}" \
        "${AUDIOLLA_BASE_URL}/v1/audio/dj-prep")
    if echo "$body" | jq -e '.detail != null' >/dev/null 2>&1; then
        echo "OK: dj_prep_missing_engine_with_bad_engines (got error: $(echo "$body" | jq -r '.detail'))"
        return 0
    fi
    # Or it worked fine (all engines available).
    if ! echo "$body" | jq -e 'has("bpm")' >/dev/null 2>&1; then
        echo "  FAIL: unexpected response shape; body: $body"; return 1
    fi
    echo "OK: dj_prep_missing_engine_with_bad_engines (all engines available)"
}

harness_run_tests \
    test_dj_prep_response_shape \
    test_dj_prep_click_track_bpm \
    test_dj_prep_lufs_is_number \
    test_dj_prep_missing_engine_with_bad_engines
