"""Pydantic schema package — generated from ``../../../openapi.yaml``.

The actual type definitions live in :mod:`audiolla.schema._generated`,
which is regenerated by ``scripts/generate_models.sh`` (``make
generate``) every time the OpenAPI spec changes.

**Do NOT hand-edit ``_generated.py``** — edits get clobbered. To change
a request/response shape, edit ``openapi.yaml`` then run
``make generate``.

This wrapper module is hand-written and exposes:

  - re-exports of every generated class (so handler code does
    ``from audiolla.schema import NormalizeRequest`` and doesn't care
    about the split)
  - subclasses for any schema that the codegen reduced to an alias
    (``X = BaseAudioInputRequest`` — FastAPI body validation needs a
    real Pydantic subclass, not an alias)
  - runtime helpers: ``validate_input_xor`` / ``validate_multi_input_xor``
    / ``validate_output_xor`` (enforced at handler boundary), plus
    ``url_to_str`` (coerce ``AnyUrl`` → ``str | None``) and
    ``format_value`` (extract scalar from ``OutputFormat`` enum)
"""

from __future__ import annotations

from fastapi import HTTPException

from ._generated import (  # noqa: F401
    AnalyzeResult,
    AudioAnalyzeRequest,
    AudioBeatSliceRequest,
    AudioBeatsRequest,
    AudioBpmMatchRequest,
    AudioChordsRequest,
    AudioChordsToMidiRequest,
    AudioClassifyRequest,
    AudioClipDetectRequest,
    AudioConcatRequest,
    AudioConvReverbRequest,
    AudioConvertRequest,
    AudioDeessRequest,
    AudioDiarizeRequest,
    AudioDjPrepRequest,
    AudioEmbedRequest,
    AudioEnhanceRequest,
    AudioEqRequest,
    AudioFadeRequest,
    AudioFingerprintRequest,
    AudioFxRequest,
    AudioInfoRequest,
    AudioKeyMatchRequest,
    AudioLDM2Request,
    AudioLoopPointRequest,
    AudioLoopRequest,
    AudioLoudnessCurveRequest,
    AudioLoudnessRequest,
    AudioMasterRequest,
    AudioMelodyRequest,
    AudioMetadataRequest,
    AudioMidSideRequest,
    AudioMixRequest,
    AudioMultibandCompressRequest,
    AudioNoiseReduceRequest,
    AudioNormalizeRequest,
    AudioOnsetsRequest,
    AudioPanRequest,
    AudioPitchCorrectRequest,
    AudioRemixRequest,
    AudioRepairRequest,
    AudioRestoreRequest,
    AudioReverseRequest,
    AudioSegmentsRequest,
    AudioSeparateHpssRequest,
    AudioSeparateRequest,
    AudioSidechainDuckRequest,
    AudioSilenceRequest,
    AudioSimilarRequest,
    AudioSpeedRequest,
    AudioSplitRequest,
    AudioStereoFieldRequest,
    AudioStereoWidthRequest,
    AudioStretchRequest,
    AudioTagRequest,
    AudioThumbnailRequest,
    AudioToMidiRequest,
    AudioTransformRequest,
    AudioTransientRequest,
    AudioTrimRequest,
    AudioVadRequest,
    AudioVisualizeImageSpectrogramRequest,
    AudioVisualizeImageWaveformRequest,
    AudioVisualizeVideoRequest,
    BaseAudioInputRequest,
    BaseAudioOutputRequest,
    BaseGenerateRequest,
    EngineInfo,
    ErrorBody,
    HealthResponse,
    JobAcceptedResponse,
    LoudnessResult,
    MidiHumanizeRequest,
    MidiInspectRequest,
    MidiQuantizeRequest,
    MidiRenderRequest,
    MidiTransformRequest,
    MultiAudioInputRequest,
    MusicGenRequest,
    NormalizeResponse,
    OutputFormat,
    RiffusionRequest,
    StableAudioOpenRequest,
    StagedOutputResponse,
    UrlOutputResponse,
)

# ── alias-class fixups ──────────────────────────────────────────────────────
# When an endpoint's only fields are the inherited ones from
# BaseAudioInputRequest (or any base), datamodel-codegen emits a type
# alias (`X = BaseAudioInputRequest`) instead of a real subclass. FastAPI's
# request-body machinery needs an actual BaseModel subclass — aliases get
# misclassified as Query parameters and crash /openapi.json generation.
# Fix by re-declaring each alias as a true subclass.

if not isinstance(AudioLoudnessRequest, type) or AudioLoudnessRequest is BaseAudioInputRequest:
    class AudioLoudnessRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioNormalizeRequest, type) or AudioNormalizeRequest is BaseAudioInputRequest:
    class AudioNormalizeRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioOnsetsRequest, type) or AudioOnsetsRequest is BaseAudioInputRequest:
    class AudioOnsetsRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioInfoRequest, type) or AudioInfoRequest is BaseAudioInputRequest:
    class AudioInfoRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioClipDetectRequest, type) or AudioClipDetectRequest is BaseAudioInputRequest:
    class AudioClipDetectRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioDjPrepRequest, type) or AudioDjPrepRequest is BaseAudioInputRequest:
    class AudioDjPrepRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(AudioStereoFieldRequest, type) or AudioStereoFieldRequest is BaseAudioInputRequest:
    class AudioStereoFieldRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass

if not isinstance(MidiInspectRequest, type) or MidiInspectRequest is BaseAudioInputRequest:
    class MidiInspectRequest(BaseAudioInputRequest):  # type: ignore[no-redef]
        pass


# Also need to handle NormalizeRequest (the canonical normalize handler
# uses a custom request with target_lufs; openapi.yaml has it as a real
# subclass). But the auto-generated AudioNormalizeRequest above is the
# alias — we keep both for backwards compat with any code still importing
# NormalizeRequest (the original canary name).
NormalizeRequest = AudioNormalizeRequest  # backwards-compat alias


__all__ = [
    "AnalyzeResult",
    "AudioAnalyzeRequest",
    "AudioBeatSliceRequest",
    "AudioBeatsRequest",
    "AudioBpmMatchRequest",
    "AudioChordsRequest",
    "AudioChordsToMidiRequest",
    "AudioClassifyRequest",
    "AudioClipDetectRequest",
    "AudioConcatRequest",
    "AudioConvReverbRequest",
    "AudioConvertRequest",
    "AudioDeessRequest",
    "AudioDiarizeRequest",
    "AudioDjPrepRequest",
    "AudioEmbedRequest",
    "AudioEnhanceRequest",
    "AudioEqRequest",
    "AudioFadeRequest",
    "AudioFingerprintRequest",
    "AudioFxRequest",
    "AudioInfoRequest",
    "AudioKeyMatchRequest",
    "AudioLDM2Request",
    "AudioLoopPointRequest",
    "AudioLoopRequest",
    "AudioLoudnessCurveRequest",
    "AudioLoudnessRequest",
    "AudioMasterRequest",
    "AudioMelodyRequest",
    "AudioMetadataRequest",
    "AudioMidSideRequest",
    "AudioMixRequest",
    "AudioMultibandCompressRequest",
    "AudioNoiseReduceRequest",
    "AudioNormalizeRequest",
    "AudioOnsetsRequest",
    "AudioPanRequest",
    "AudioPitchCorrectRequest",
    "AudioRemixRequest",
    "AudioRepairRequest",
    "AudioRestoreRequest",
    "AudioReverseRequest",
    "AudioSegmentsRequest",
    "AudioSeparateHpssRequest",
    "AudioSeparateRequest",
    "AudioSidechainDuckRequest",
    "AudioSilenceRequest",
    "AudioSimilarRequest",
    "AudioSpeedRequest",
    "AudioSplitRequest",
    "AudioStereoFieldRequest",
    "AudioStereoWidthRequest",
    "AudioStretchRequest",
    "AudioTagRequest",
    "AudioThumbnailRequest",
    "AudioToMidiRequest",
    "AudioTransformRequest",
    "AudioTransientRequest",
    "AudioTrimRequest",
    "AudioVadRequest",
    "AudioVisualizeImageSpectrogramRequest",
    "AudioVisualizeImageWaveformRequest",
    "AudioVisualizeVideoRequest",
    "BaseAudioInputRequest",
    "BaseAudioOutputRequest",
    "BaseGenerateRequest",
    "EngineInfo",
    "ErrorBody",
    "HealthResponse",
    "JobAcceptedResponse",
    "LoudnessResult",
    "MidiHumanizeRequest",
    "MidiInspectRequest",
    "MidiQuantizeRequest",
    "MidiRenderRequest",
    "MidiTransformRequest",
    "MultiAudioInputRequest",
    "MusicGenRequest",
    "NormalizeRequest",
    "NormalizeResponse",
    "OutputFormat",
    "RiffusionRequest",
    "StableAudioOpenRequest",
    "StagedOutputResponse",
    "UrlOutputResponse",
    "format_value",
    "url_to_str",
    "validate_input_xor",
    "validate_multi_input_xor",
    "validate_output_xor",
]


# ── coercion helpers ───────────────────────────────────────────────────────

def url_to_str(url) -> str | None:
    """Coerce a Pydantic ``AnyUrl`` to a plain string for downstream
    helpers that expect ``str | None``. Returns None for None input."""
    if url is None:
        return None
    return str(url)


def format_value(fmt) -> str:
    """Extract the string value from an ``OutputFormat`` enum (or pass
    through a plain string). Lets handlers pass the same value to both
    ``content_type_for(fmt)`` and the engine's ``output_format=`` kwarg
    regardless of how the field was parsed."""
    if hasattr(fmt, "value"):
        return fmt.value
    return str(fmt)


# ── runtime xor validators ─────────────────────────────────────────────────
#
# Pydantic's `oneOf` JSON Schema construct doesn't survive datamodel-codegen
# inheritance — child schemas lose the parent's fields when the parent has a
# top-level oneOf. So the YAML keeps both fields nullable, and these helpers
# enforce the xor at the handler boundary. Every audio handler calls one of
# them right after Pydantic validation.

def validate_input_xor(file_path: str | None, file_url) -> None:
    """Enforce exactly one of file_path / file_url. Raises HTTPException(400)
    on violation."""
    n = int(bool(file_path)) + int(bool(file_url))
    if n == 0:
        raise HTTPException(
            status_code=400,
            detail="must provide exactly one of: file_path, file_url",
        )
    if n > 1:
        raise HTTPException(
            status_code=400,
            detail="file_path and file_url are mutually exclusive",
        )


def validate_multi_input_xor(
    file_paths: list[str] | None,
    file_urls,
) -> None:
    """Enforce exactly one of file_paths / file_urls (non-empty list)."""
    has_paths = file_paths is not None and len(file_paths) > 0
    has_urls = file_urls is not None and len(file_urls) > 0
    if not has_paths and not has_urls:
        raise HTTPException(
            status_code=400,
            detail="must provide exactly one of: file_paths, file_urls (non-empty list)",
        )
    if has_paths and has_urls:
        raise HTTPException(
            status_code=400,
            detail="file_paths and file_urls are mutually exclusive",
        )


def validate_output_xor(
    output_path: str | None,
    output_url,
    *,
    async_job: bool,
) -> None:
    """Enforce output destination on an audio-producing endpoint.

    - sync mode: exactly one of output_path / output_url is required
    - async mode: both optional (server auto-generates jobs/{id}.{ext})

    Either way: providing BOTH is rejected as mutually exclusive."""
    has_path = bool(output_path)
    has_url = bool(output_url)
    if has_path and has_url:
        raise HTTPException(
            status_code=400,
            detail="output_path and output_url are mutually exclusive",
        )
    if async_job:
        return
    if not has_path and not has_url:
        raise HTTPException(
            status_code=400,
            detail=(
                "audio-producing endpoint requires output_path or output_url "
                "(sync mode); use async_job=true for auto-staged "
                "jobs/{id}.{ext}"
            ),
        )
