# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-31T15:15:03+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, Field, RootModel


class ErrorBody(BaseModel):
    detail: Annotated[str, Field(description='Human-readable error description.')]


class AudioBlob(RootModel[bytes]):
    root: Annotated[
        bytes, Field(description='Raw audio bytes in the requested output format.')
    ]


class StagedOutputResponse(BaseModel):
    path: Annotated[
        str,
        Field(
            description='Relative path under the staging area (resolves to FILES_DIR / path on disk).'
        ),
    ]
    size: Annotated[int, Field(description='Bytes written.')]
    output_format: Annotated[
        str | None, Field(description='Echo of the requested output_format.')
    ] = None


class UrlOutputResponse(BaseModel):
    url: Annotated[
        AnyUrl, Field(description='The presigned PUT URL the bytes were uploaded to.')
    ]
    size: Annotated[int, Field(description='Bytes uploaded.')]
    output_format: Annotated[
        str | None, Field(description='Echo of the requested output_format.')
    ] = None


class EngineInfo(BaseModel):
    slug: Annotated[
        str, Field(description='Unique engine identifier (key in engines.json).')
    ]
    executor: Annotated[
        str,
        Field(
            description='Backend type (demucs, matchering, pedalboard_chain, librosa_analyze, sox_transform).'
        ),
    ]
    variant: Annotated[
        str | None,
        Field(
            description='Demucs model variant (htdemucs, htdemucs_ft, etc.). Null for non-demucs engines.'
        ),
    ] = None
    stems: Annotated[
        list[str] | None,
        Field(description='Available stem names. Populated for demucs engines only.'),
    ] = None
    presets: Annotated[
        list[str] | None,
        Field(
            description='Available preset names. Populated for pedalboard-chain only.'
        ),
    ] = None
    description: str | None = None


class AnalyzeResult(BaseModel):
    bpm: Annotated[
        float | None, Field(description='Estimated tempo in beats per minute.')
    ] = None
    key: Annotated[
        str | None,
        Field(description='Estimated musical key (e.g. "C major", "A minor").'),
    ] = None
    loudness_lufs: Annotated[
        float | None,
        Field(description='Integrated loudness in LUFS (ITU-R BS.1770-4).'),
    ] = None
    duration: Annotated[float | None, Field(description='Duration in seconds.')] = None
    spectral_centroid: Annotated[
        float | None, Field(description='Mean spectral centroid in Hz.')
    ] = None
    rms: Annotated[float | None, Field(description='Root mean square energy.')] = None
    zcr: Annotated[float | None, Field(description='Mean zero-crossing rate.')] = None


class LoudnessResult(BaseModel):
    loudness_lufs: Annotated[
        float, Field(description='Measured integrated loudness in LUFS.')
    ]
    target_lufs: Annotated[
        float | None,
        Field(
            description='The requested target_lufs (echoed back). Null if analyze-only.'
        ),
    ] = None
    normalized: Annotated[
        bool | None,
        Field(description='True if normalization was applied, false for analyze-only.'),
    ] = None


class Op(Enum):
    gain = 'gain'
    equalizer = 'equalizer'
    compand = 'compand'
    reverb = 'reverb'
    pitch = 'pitch'
    tempo = 'tempo'
    rate = 'rate'
    channels = 'channels'
    trim = 'trim'
    pad = 'pad'


class SoxOperation(BaseModel):
    op: Annotated[Op, Field(description='SoX effect name.')]
    params: Annotated[
        dict[str, Any] | None,
        Field(
            description="Effect-specific parameters. See SoX documentation for each effect's options."
        ),
    ] = None


class HealthResponse(BaseModel):
    ok: bool
    device: Annotated[
        str, Field(description='Active compute device (cpu, cuda, cuda:N).')
    ]
    engines: Annotated[list[str], Field(description='Configured engine slugs.')]


class PsEntry(BaseModel):
    slug: str
    executor: str
    loaded: bool
    idle_seconds: float | None = None
