# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-08T18:27:35+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, Field, RootModel


class ErrorBody(BaseModel):
    detail: str


class OutputFormat(Enum):
    wav = 'wav'
    mp3 = 'mp3'
    flac = 'flac'
    opus = 'opus'
    aac = 'aac'
    pcm = 'pcm'


class AudioBlob(RootModel[bytes]):
    root: bytes


class BaseAudioInputRequest(BaseModel):
    file_path: Annotated[
        str | None,
        Field(
            description='FILES_DIR-relative path (pre-staged via PUT /v1/files/{path}).'
        ),
    ] = None
    file_url: Annotated[
        AnyUrl | None,
        Field(
            description='HTTP/HTTPS URL the server fetches (subject to AUDIOLLA_FETCH_MODE).'
        ),
    ] = None


class MultiAudioInputRequest(BaseModel):
    file_paths: Annotated[list[str] | None, Field(min_length=1)] = None
    file_urls: list[AnyUrl] | None = None


class BaseAudioOutputRequest(BaseModel):
    output_format: OutputFormat = 'wav'
    output_path: Annotated[
        str | None,
        Field(
            description='FILES_DIR-relative path; response is JSON {path, size, ...}.'
        ),
    ] = None
    output_url: Annotated[
        AnyUrl | None,
        Field(
            description='Presigned PUT URL (S3, hybrids3, MinIO, R2, etc.) — response is JSON {url, size, ...}.'
        ),
    ] = None
    async_job: bool = False
    webhook_url: AnyUrl | None = None


class BaseGenerateRequest(BaseModel):
    prompt: Annotated[str, Field(min_length=1)]
    duration_sec: Annotated[float, Field(ge=0.001)] = 10.0
    seed: int | None = None


class StagedOutputResponse(BaseModel):
    path: str
    size: int
    output_format: str | None = None


class UrlOutputResponse(BaseModel):
    url: AnyUrl
    size: int
    output_format: str | None = None


class JobAcceptedResponse(BaseModel):
    job_id: str
    status_url: AnyUrl


class NormalizeResponse(StagedOutputResponse):
    target_lufs: float | None = None
    measured_lufs: float | None = None


class AnalyzeResult(BaseModel):
    bpm: float | None = None
    key: str | None = None
    loudness_lufs: float | None = None
    duration: float | None = None
    spectral_centroid: float | None = None
    rms: float | None = None
    zcr: float | None = None


class LoudnessResult(BaseModel):
    loudness_lufs: float
    target_lufs: float | None = None
    normalized: bool | None = None


class HealthResponse(BaseModel):
    ok: bool
    device: str
    engines: list[str]


class EngineInfo(BaseModel):
    slug: str
    executor: str
    variant: str | None = None
    stems: list[str] | None = None
    presets: list[str] | None = None
    loaded: bool | None = None
    idle_seconds: float | None = None
    description: str | None = None


class AudioSeparateRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    engine: Annotated[
        str,
        Field(
            description='Stem-separation engine slug. Demucs (`htdemucs`,\n`htdemucs_ft`, `mdx_extra`) or UVR variant\n(`uvr-vocal-bsr`, `uvr-karaoke`, `uvr-dereverb`, etc.).\n'
        ),
    ]
    stems: Annotated[
        list[str],
        Field(description='Subset of stems to return. Empty = all available stems.'),
    ] = []


class Mode(Enum):
    reference = 'reference'
    chain = 'chain'


class AudioMasterRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    mode: Mode
    reference_path: str | None = None
    reference_url: AnyUrl | None = None
    preset: str | None = None
    target_lufs: float | None = None


class AudioAnalyzeRequest(BaseAudioInputRequest):
    features: list[str] = []


class Operation(BaseModel):
    op: str | None = None
    params: dict[str, Any] | None = None


class AudioTransformRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    operations: Annotated[
        list[Operation],
        Field(description='SoX effect chain — each entry is {op, params}.'),
    ]


AudioLoudnessRequest = BaseAudioInputRequest


class AudioNormalizeRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    target_lufs: float


class Effect(BaseModel):
    type: str | None = None
    params: dict[str, Any] | None = None


class AudioFxRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    effects: Annotated[
        list[Effect],
        Field(description='Pedalboard effect chain — each entry is {type, params}.'),
    ]


class MidiRenderRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    soundfont_path: str | None = None
    gain: float = 0.5
    samplerate: int = 44100


class AudioBeatsRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    click_track: bool = False
    start_bpm: float | None = None


AudioOnsetsRequest = BaseAudioInputRequest


class AudioMelodyRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    fmin: float = 65.0
    fmax: float = 2093.0
    as_midi: bool = False


class AudioSegmentsRequest(BaseAudioInputRequest):
    num_segments: int = 6


class AudioSilenceRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    threshold_db: float = -30.0
    min_duration_sec: float = 0.5
    trim_mode: str | None = None


class AudioVisualizeImageSpectrogramRequest(
    BaseAudioInputRequest, BaseAudioOutputRequest
):
    width: int = 1280
    height: int = 720
    color: str = 'intensity'
    scale: str = 'log'


class AudioVisualizeImageWaveformRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    width: int = 1280
    height: int = 720
    color: str = 'lime'


class AudioVisualizeVideoRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    width: int = 1280
    height: int = 720
    fps: int = 30
    container: str = 'mp4'


class AudioFingerprintRequest(BaseAudioInputRequest):
    analyze_seconds: float = 120.0
    return_raw: bool = False


class AudioRestoreRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    aggressive: bool = False


MidiInspectRequest = BaseAudioInputRequest


class MidiTransformRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    transpose_semitones: int = 0
    quantize_grid_beats: float | None = None
    tempo_bpm: float | None = None
    keep_channels: str | None = None
    drop_channels: str | None = None


class AudioToMidiRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    onset_threshold: float = 0.5
    frame_threshold: float = 0.3
    minimum_note_length_ms: float = 58.0
    minimum_frequency: float | None = None
    maximum_frequency: float | None = None
    multiple_pitch_bends: bool = False
    melodia_trick: bool = True


class AudioEnhanceRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    pass


class AudioChordsRequest(BaseAudioInputRequest):
    hop_length: int = 512
    segment_min_duration_sec: float = 0.5


class AudioVadRequest(BaseAudioInputRequest):
    threshold: float = 0.5
    min_speech_duration_ms: float = 250.0
    min_silence_duration_ms: float = 100.0


class AudioDiarizeRequest(BaseAudioInputRequest):
    num_speakers: int | None = None
    min_speakers: int | None = None
    max_speakers: int | None = None


class AudioStretchRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    tempo_factor: float = 1.0
    pitch_semitones: float = 0.0


class AudioTagRequest(BaseAudioInputRequest):
    top_k: int = 10


class AudioEmbedRequest(BaseAudioInputRequest):
    query_text: str | None = None


class AudioSeparateHpssRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    margin: float = 1.0
    kernel_size: int = 31


class AudioNoiseReduceRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    stationary: bool = False
    prop_decrease: float = 1.0


AudioInfoRequest = BaseAudioInputRequest


class AudioTrimRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    start_sec: float = 0.0
    end_sec: float


class AudioMixRequest(MultiAudioInputRequest, BaseAudioOutputRequest):
    pass


class AudioConcatRequest(MultiAudioInputRequest, BaseAudioOutputRequest):
    pass


class AudioSpeedRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    speed: float


class AudioConvertRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    sample_rate: int | None = None
    channels: int | None = None


class AudioSimilarRequest(BaseAudioInputRequest):
    reference_file_path: str | None = None
    reference_file_url: str | None = None


class MidiQuantizeRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    grid_beats: float = 0.25


class AudioClassifyRequest(BaseAudioInputRequest):
    labels: Annotated[
        list[str],
        Field(description='Candidate label strings to score the audio against.'),
    ]


class AudioFadeRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    fade_in: float = 0.0
    fade_out: float = 0.0
    curve: str = 'tri'


class AudioReverseRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    pass


class AudioLoopRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    count: int = 2


class AudioBpmMatchRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    target_bpm: float
    pitch_semitones: float = 0.0


class AudioStereoWidthRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    width: float = 1.0


class Mode1(Enum):
    equal = 'equal'
    silence = 'silence'


class AudioSplitRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    mode: Mode1 = 'equal'
    count: int | None = None
    threshold_db: float = -30.0
    min_duration_sec: float = 0.5


class AudioPanRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    position: float = 0.0


class AudioEqRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    bands: Annotated[
        list[dict[str, Any]],
        Field(description='Array of band specifications (object per band).'),
    ]


class AudioKeyMatchRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    target_key: str


class AudioSidechainDuckRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    trigger_file_path: str | None = None
    trigger_file_url: str | None = None
    threshold_db: float = -20.0
    ratio: float = 4.0
    attack_ms: float = 10.0
    release_ms: float = 200.0


class AudioMetadataRequest(BaseAudioInputRequest):
    tags: str | None = None


AudioClipDetectRequest = BaseAudioInputRequest


class Mode2(Enum):
    encode = 'encode'
    decode = 'decode'


class AudioMidSideRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    mode: Mode2


class AudioBeatSliceRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    pass


class AudioConvReverbRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    ir_file_path: str | None = None
    ir_file_url: str | None = None
    wet_mix: float = 0.3


class AudioTransientRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    attack_gain_db: float = 0.0
    sustain_gain_db: float = 0.0


class AudioMultibandCompressRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    crossovers_hz: Annotated[
        list[float],
        Field(
            description='Ascending crossover frequencies (Hz). 1 fewer than the number of bands.'
        ),
    ]
    bands: Annotated[
        list[dict[str, Any]],
        Field(description='Array of band specifications (object per band).'),
    ]


class AudioRemixRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    engine: Annotated[
        str, Field(description='Stem-separation engine for the unmix step.')
    ] = 'htdemucs'
    stem_mix: Annotated[
        dict[str, float] | None,
        Field(
            description="Per-stem gain dict — keys are stem names ('vocals', 'drums',\n'bass', 'other'), values are linear gain multipliers (1.0 =\nkeep, 0.0 = mute, 0.5 = -6 dB). Missing stems default to 1.0.\n"
        ),
    ] = None


AudioDjPrepRequest = BaseAudioInputRequest


class AudioLoudnessCurveRequest(BaseAudioInputRequest):
    hop_length: int = 512


class AudioPitchCorrectRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    strength: float = 1.0


class AudioRepairRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    declip: bool = True
    dehum: bool = False
    hum_freq: float = 50.0


class AudioLoopPointRequest(BaseAudioInputRequest):
    min_loop_bars: int = 4
    num_candidates: int = 5


class AudioChordsToMidiRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    tempo_bpm: float | None = None
    velocity: int = 80
    octave: int = 4


class AudioDeessRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    threshold_db: float = -20.0
    frequency_hz: float = 6000.0
    ratio: float = 4.0


AudioStereoFieldRequest = BaseAudioInputRequest


class AudioThumbnailRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    duration_sec: float = 30.0


class MidiHumanizeRequest(BaseAudioInputRequest, BaseAudioOutputRequest):
    timing_ms: float = 10.0
    velocity_pct: float = 10.0
    seed: int | None = None


class StableAudioOpenRequest(BaseGenerateRequest, BaseAudioOutputRequest):
    num_inference_steps: Annotated[int, Field(ge=1, le=500)] = 100
    negative_prompt: str = 'low quality, average quality'


class MusicGenRequest(BaseGenerateRequest, BaseAudioOutputRequest):
    lyrics: Annotated[
        str | None,
        Field(
            description='Accepted for API uniformity; MusicGen is instrumental-only.'
        ),
    ] = None


class RiffusionRequest(BaseGenerateRequest, BaseAudioOutputRequest):
    pass


class AudioLDM2Request(BaseGenerateRequest, BaseAudioOutputRequest):
    num_inference_steps: Annotated[int, Field(ge=1, le=500)] = 200
    negative_prompt: str = 'Low quality.'
